package photo

var allPhoto = map[string]Photo{
	"一寸照": {
		PhotoName:     "一寸照",
		PhotoFileSize: "150~300kb",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"二寸照": {
		PhotoName:     "二寸照",
		PhotoFileSize: "",
		WidthMm:       35,
		HeightMm:      49,
		WidthPx:       413,
		HeightPx:      579,
	},
	"小一寸": {
		PhotoName:     "小一寸",
		PhotoFileSize: "",
		WidthMm:       22,
		HeightMm:      32,
		WidthPx:       259,
		HeightPx:      377,
	},
	"小二寸": {
		PhotoName:     "小二寸",
		PhotoFileSize: "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"大一寸": {
		PhotoName:     "大一寸",
		PhotoFileSize: "",
		WidthMm:       33,
		HeightMm:      48,
		WidthPx:       389,
		HeightPx:      566,
	},
	"大二寸": {
		PhotoName:     "大二寸",
		PhotoFileSize: "",
		WidthMm:       35,
		HeightMm:      53,
		WidthPx:       413,
		HeightPx:      625,
	},
	"三寸照": {
		PhotoName:     "三寸照",
		PhotoFileSize: "",
		WidthMm:       55,
		HeightMm:      84,
		WidthPx:       649,
		HeightPx:      992,
	},
	"四寸照": {
		PhotoName:     "四寸照",
		PhotoFileSize: "",
		WidthMm:       76,
		HeightMm:      102,
		WidthPx:       897,
		HeightPx:      1204,
	},
	//////////////////////////////////////////////
	"学士学位照": {
		PhotoName:     "学士学位照",
		PhotoFileSize: "<=10kb",
		WidthMm:       33,
		HeightMm:      48,
		WidthPx:       389,
		HeightPx:      566,
	},
	"学历证书照": {
		PhotoName:     "学历证书照",
		PhotoFileSize: "<=10kb",
		WidthMm:       33,
		HeightMm:      48,
		WidthPx:       389,
		HeightPx:      566,
	},
	"成人自考电子照": {
		PhotoName:     "成人自考",
		PhotoFileSize: "<=30kb",
		PhotoDes:      "电子照",
		WidthMm:       33,
		HeightMm:      40,
		WidthPx:       389,
		HeightPx:      472,
	},

	"毕业照大学": {
		PhotoName:     "毕业照",
		PhotoFileSize: "",
		PhotoDes:      "大学",
		WidthMm:       35,
		HeightMm:      49,
		WidthPx:       413,
		HeightPx:      578,
	},
	"毕业照高中": {
		PhotoName:     "毕业照",
		PhotoFileSize: "",
		PhotoDes:      "高中",
		WidthMm:       35,
		HeightMm:      49,
		WidthPx:       413,
		HeightPx:      578,
	},
	"毕业照初中": {
		PhotoName:     "毕业照",
		PhotoFileSize: "",
		PhotoDes:      "初中",
		WidthMm:       35,
		HeightMm:      49,
		WidthPx:       413,
		HeightPx:      578,
	},
	"学生照中小学": {
		PhotoName:     "学生照",
		PhotoFileSize: "<=60kb",
		PhotoDes:      "中小学",
		WidthMm:       26,
		HeightMm:      32,
		WidthPx:       307,
		HeightPx:      377,
	},

	"入学照香港": {
		PhotoName:     "入学照",
		PhotoFileSize: "<=400kb",
		PhotoDes:      "香港",
		WidthMm:       38,
		HeightMm:      40,
		WidthPx:       448,
		HeightPx:      472,
	},
	"入学照大学": {
		PhotoName:     "入学照",
		PhotoFileSize: "<=400kb",
		PhotoDes:      "大学",
		WidthMm:       26,
		HeightMm:      32,
		WidthPx:       307,
		HeightPx:      377,
	},
	"入学照小学": {
		PhotoName:     "入学照",
		PhotoFileSize: "<=500kb",
		PhotoDes:      "小学",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"入学照初中": {
		PhotoName:     "入学照",
		PhotoFileSize: "<=60kb",
		PhotoDes:      "初中",
		WidthMm:       26,
		HeightMm:      32,
		WidthPx:       307,
		HeightPx:      377,
	},
	"入学照幼儿": {
		PhotoName:     "入学照",
		PhotoFileSize: "",
		PhotoDes:      "幼儿",
		WidthMm:       26,
		HeightMm:      32,
		WidthPx:       307,
		HeightPx:      377,
	},
	"高考报名": {
		PhotoName:     "高考报名",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       41,
		HeightMm:      54,
		WidthPx:       484,
		HeightPx:      637,
	},
	//////////////////////////////////////////////

	"21年注会考试": {
		PhotoName:     "21年注会考试",
		PhotoFileSize: "10~20kb",
		PhotoDes:      "",
		WidthMm:       8,
		HeightMm:      10,
		WidthPx:       102,
		HeightPx:      126,
	},

	"税务师考试": {
		PhotoName:     "税务师考试",
		PhotoFileSize: "5~30kb",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"会计师注会": {
		PhotoName:     "会计师",
		PhotoFileSize: "2~20kb",
		PhotoDes:      "注会",
		WidthMm:       15,
		HeightMm:      19,
		WidthPx:       178,
		HeightPx:      220,
	},
	"韩语考试": {
		PhotoName:     "韩语考试",
		PhotoFileSize: "20~200kb",
		PhotoDes:      "",
		WidthMm:       30,
		HeightMm:      40,
		WidthPx:       354,
		HeightPx:      472,
	},
	"日语考试": {
		PhotoName:     "日语考试",
		PhotoFileSize: "20~200kb",
		PhotoDes:      "",
		WidthMm:       30,
		HeightMm:      40,
		WidthPx:       354,
		HeightPx:      472,
	},
	"计算机考试": {
		PhotoName:     "计算机考试",
		PhotoFileSize: "20~200kb",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"公务员考试": {
		PhotoName:     "公务员考试",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"医护英语": {
		PhotoName:     "医护英语",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      38,
		WidthPx:       295,
		HeightPx:      448,
	},
	"商务英语": {
		PhotoName:     "商务英语",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      34,
		WidthPx:       295,
		HeightPx:      401,
	},
	"学位英语": {
		PhotoName:     "学位英语",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       33,
		HeightMm:      48,
		WidthPx:       389,
		HeightPx:      566,
	},
	"英语三级": {
		PhotoName:     "英语三级",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       33,
		HeightMm:      48,
		WidthPx:       389,
		HeightPx:      566,
	},
	"英语四六级1": {
		PhotoName:     "英语四六级",
		PhotoFileSize: "<=50kb",
		PhotoDes:      "",
		WidthMm:       26,
		HeightMm:      37,
		WidthPx:       389,
		HeightPx:      566,
	},
	"英语四六级2": {
		PhotoName:     "英语四六级",
		PhotoFileSize: "<=60kb",
		PhotoDes:      "",
		WidthMm:       12,
		HeightMm:      16,
		WidthPx:       141,
		HeightPx:      188,
	},
	"英语四六级3": {
		PhotoName:     "英语四六级",
		PhotoFileSize: "20~100kb",
		PhotoDes:      "",
		WidthMm:       20,
		HeightMm:      27,
		WidthPx:       236,
		HeightPx:      318,
	},
	"特岗教师": {
		PhotoName:     "特岗教师",
		PhotoFileSize: "<=200kb",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"幼师资格证": {
		PhotoName:     "幼师资格证",
		PhotoFileSize: "<=200kb",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"教师证中小学": {
		PhotoName:     "教师证",
		PhotoFileSize: "<=200kb",
		PhotoDes:      "中小学",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"教师资格证": {
		PhotoName:     "教师资格证",
		PhotoFileSize: "<=200kb",
		PhotoDes:      "中小学",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"护士证电子": {
		PhotoName:     "护士证",
		PhotoFileSize: "20~80kb",
		PhotoDes:      "电子",
		WidthMm:       30,
		HeightMm:      40,
		WidthPx:       354,
		HeightPx:      472,
	},
	"护士证资格证": {
		PhotoName:     "护士证",
		PhotoFileSize: "",
		PhotoDes:      "资格证",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"护士考试": {
		PhotoName:     "护士考试",
		PhotoFileSize: "20~45kb",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},

	"会计师高级": {
		PhotoName:     "会计师",
		PhotoFileSize: "10~30kb",
		PhotoDes:      "高级",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"会计师中级": {
		PhotoName:     "会计师",
		PhotoFileSize: "<30kb",
		PhotoDes:      "中级",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"会计师初级": {
		PhotoName:     "会计师",
		PhotoFileSize: "<=10kb",
		PhotoDes:      "初级",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},

	//////////////////////////////////////////////

	"国家司法考试": {
		PhotoName:     "国家司法考试",
		PhotoFileSize: "40~100kb",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      53,
		WidthPx:       413,
		HeightPx:      626,
	},

	"二级建造师证": {
		PhotoName:     "二级建造师证",
		PhotoFileSize: "30~40kb",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      34,
		WidthPx:       295,
		HeightPx:      401,
	},
	"一级建造师证冲印版": {
		PhotoName:     "一级建造师证",
		PhotoFileSize: "",
		PhotoDes:      "冲印版",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"一级建造师证电子版": {
		PhotoName:     "一级建造师证",
		PhotoFileSize: "",
		PhotoDes:      "电子版",
		WidthMm:       34,
		HeightMm:      45,
		WidthPx:       401,
		HeightPx:      531,
	},

	"健康证": {
		PhotoName:     "健康证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"警官证": {
		PhotoName:     "健康证",
		PhotoFileSize: "40~150kb",
		PhotoDes:      "",
		WidthMm:       34,
		HeightMm:      45,
		WidthPx:       401,
		HeightPx:      513,
	},
	"人力资源管理师": {
		PhotoName:     "人力资源管理师",
		PhotoFileSize: "40~80kb",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      49,
		WidthPx:       413,
		HeightPx:      578,
	},
	"人力资源资格证": {
		PhotoName:     "人力资源资格证",
		PhotoFileSize: "<20kb",
		PhotoDes:      "",
		WidthMm:       14,
		HeightMm:      18,
		WidthPx:       165,
		HeightPx:      212,
	},
	"建造师": {
		PhotoName:     "建造师",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       33,
		HeightMm:      48,
		WidthPx:       389,
		HeightPx:      566,
	},
	"雅思": {
		PhotoName:     "雅思",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       33,
		HeightMm:      48,
		WidthPx:       389,
		HeightPx:      566,
	},
	"普通话": {
		PhotoName:     "普通话",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       33,
		HeightMm:      48,
		WidthPx:       389,
		HeightPx:      566,
	},
	"医师资格考试": {
		PhotoName:     "医师资格考试",
		PhotoFileSize: "25~40kb",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},

	"考研照": {
		PhotoName:     "考研照",
		PhotoFileSize: "20~200kb",
		PhotoDes:      "",
		WidthMm:       33,
		HeightMm:      48,
		WidthPx:       389,
		HeightPx:      566,
	},
	"法律资格证": {
		PhotoName:     "法律资格证",
		PhotoFileSize: "<200kb",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      53,
		WidthPx:       413,
		HeightPx:      625,
	},

	//////////////////////////////////////////////

	"新西兰签证": {
		PhotoName:     "新西兰签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       76,
		HeightMm:      102,
		WidthPx:       897,
		HeightPx:      1024,
	},
	"文莱签证": {
		PhotoName:     "文莱签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"挪威签证": {
		PhotoName:     "挪威签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"俄罗斯签证": {
		PhotoName:     "俄罗斯签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"意大利签证": {
		PhotoName:     "意大利签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"瑞士签证": {
		PhotoName:     "瑞士签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"澳大利亚签证": {
		PhotoName:     "澳大利亚签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"法国签证": {
		PhotoName:     "法国签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"越南签证": {
		PhotoName:     "越南签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"日本护照": {
		PhotoName:     "日本护照",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"韩国签证": {
		PhotoName:     "韩国签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"英国签证": {
		PhotoName:     "英国签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       35,
		HeightMm:      45,
		WidthPx:       413,
		HeightPx:      531,
	},
	"美国签证": {
		PhotoName:     "美国签证",
		PhotoFileSize: "<240kb",
		PhotoDes:      "",
		WidthMm:       51,
		HeightMm:      51,
		WidthPx:       602,
		HeightPx:      602,
	},
	"日本签证": {
		PhotoName:     "日本签证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       45,
		HeightMm:      45,
		WidthPx:       531,
		HeightPx:      531,
	},
	/////////////////////////////

	"简历照": {
		PhotoName:     "简历照",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"学生证": {
		PhotoName:     "学生证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       25,
		HeightMm:      35,
		WidthPx:       295,
		HeightPx:      413,
	},
	"驾驶证": {
		PhotoName:     "驾驶证",
		PhotoFileSize: "",
		PhotoDes:      "",
		WidthMm:       22,
		HeightMm:      32,
		WidthPx:       259,
		HeightPx:      377,
	},
}

var AllGroupPhoto = []PhotoGroup{

	{
		GroupName: Normal,
		Photos: []Photo{
			allPhoto["一寸照"],
			allPhoto["二寸照"],
			allPhoto["小一寸"],
			allPhoto["小二寸"],
			allPhoto["大一寸"],
			allPhoto["大二寸"],
			allPhoto["三寸照"],
			allPhoto["四寸照"],
		},
	},
	{
		GroupName: Student,
		Photos: []Photo{
			allPhoto["学士学位照"],
			allPhoto["学历证书照"],
			allPhoto["成人自考电子照"],
			allPhoto["毕业照大学"],
			allPhoto["毕业照高中"],
			allPhoto["毕业照初中"],
			allPhoto["学生照中小学"],
			allPhoto["入学照香港"],
			allPhoto["入学照大学"],
			allPhoto["入学照小学"],
			allPhoto["入学照初中"],
			allPhoto["入学照幼儿"],
			allPhoto["高考报名"],
		},
	},
	{
		GroupName: Exam,
		Photos: []Photo{
			allPhoto["21年注会考试"],
			allPhoto["税务师考试"],
			allPhoto["会计师注会"],
			allPhoto["韩语考试"],
			allPhoto["日语考试"],
			allPhoto["计算机考试"],
			allPhoto["公务员考试"],
			allPhoto["医护英语"],
			allPhoto["商务英语"],
			allPhoto["学位英语"],
			allPhoto["英语三级"],
			allPhoto["英语四六级1"],
			allPhoto["英语四六级2"],
			allPhoto["英语四六级3"],
			allPhoto["特岗教师"],
			allPhoto["幼师资格证"],
			allPhoto["教师证中小学"],
			allPhoto["教师资格证"],
			allPhoto["护士证电子"],
			allPhoto["护士证资格证"],
			allPhoto["护士考试"],
			allPhoto["会计师高级"],
			allPhoto["会计师中级"],
			allPhoto["会计师初级"],
		},
	},
	{
		GroupName: ID,
		Photos: []Photo{
			allPhoto["国家司法考试"],
			allPhoto["二级建造师证"],
			allPhoto["一级建造师证冲印版"],
			allPhoto["一级建造师证电子版"],
			allPhoto["健康证"],
			allPhoto["警官证"],
			allPhoto["人力资源管理师"],
			allPhoto["人力资源资格证"],
			allPhoto["建造师"],
			allPhoto["雅思"],
			allPhoto["普通话"],
			allPhoto["医师资格考试"],
			allPhoto["考研照"],
			allPhoto["法律资格证"],
		},
	},
	{
		GroupName: Signed,
		Photos: []Photo{
			allPhoto["新西兰签证"],
			allPhoto["文莱签证"],
			allPhoto["挪威签证"],
			allPhoto["俄罗斯签证"],
			allPhoto["意大利签证"],
			allPhoto["瑞士签证"],
			allPhoto["澳大利亚签证"],
			allPhoto["法国签证"],
			allPhoto["越南签证"],
			//allPhoto["泰国签证"],
			allPhoto["日本护照"],
			allPhoto["韩国签证"],
			allPhoto["英国签证"],
			allPhoto["日本签证"],
		},
	},
	PhotoGroup{
		GroupName: Other,
		Photos: []Photo{
			allPhoto["简历照"],
		},
	},
}

var HotPhoto = []Photo{
	allPhoto["小一寸"],
	allPhoto["小二寸"],
	allPhoto["驾驶证"],
	allPhoto["学生证"],
	allPhoto["成人自考电子照"],
	allPhoto["国家司法考试"],
}
